# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v14
      uses: actions/setup-node@v1
      with:
        node-version: v14
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: upload dist folder
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Download dist folder
    - uses: actions/download-artifact@v2
      with:
        name: dist
    - name: Deploy
      uses: reggionick/s3-deploy@v3
      with:
        folder: dist
        bucket: ${{ secrets.S3_BUCKET }}
        bucket-region: ${{ secrets.S3_BUCKET_REGION }}
        invalidation: /
        delete-removed: true
        no-cache: true
        private: true    
